// Generated stable language order. Luke Steuber, MIT.
#pragma once
#define LANGUAGE_COUNT 13
static const uint32_t language_resources[]={0,RESOURCE_ID_LANG_DE,RESOURCE_ID_LANG_FR,RESOURCE_ID_LANG_IT,RESOURCE_ID_LANG_ES,RESOURCE_ID_LANG_PT,RESOURCE_ID_LANG_NL,RESOURCE_ID_LANG_SV,RESOURCE_ID_LANG_UK,RESOURCE_ID_LANG_JA,RESOURCE_ID_LANG_ZH,RESOURCE_ID_LANG_KO,RESOURCE_ID_LANG_AR};
