// Generated by scripts/pebble-themes/generate.py. Luke Steuber, MIT.
#pragma once
#include <pebble.h>
#include <message_keys.auto.h>
extern uint8_t face_theme;
enum { THEME_BG, THEME_INK, THEME_A1, THEME_A2, THEME_A3, THEME_MUTED, THEME_SURFACE, THEME_EDGE, THEME_PLAY };
#define THEME_COUNT 4
static const uint32_t theme_colors[THEME_COUNT][9] = {
  {0x000000, 0xffffff, 0xffffff, 0xffffff, 0xffffff, 0xaaaaaa, 0x000000, 0xffffff, 0xffffff},
  {0xffffaa, 0x000000, 0x000000, 0x000000, 0x000000, 0x555555, 0xffffaa, 0x000000, 0x000000},
  {0x000000, 0xffffaa, 0xffffaa, 0xffffaa, 0xffffaa, 0xaaaa55, 0x000000, 0xffffff, 0xffffff},
  {0x000000, 0x55ffff, 0x55ffff, 0x55ffff, 0x55ffff, 0xaaaaaa, 0x000000, 0xffffff, 0xffffff}
};
static const bool theme_light[THEME_COUNT] = {false, true, false, false};
// Theme ID is independent of language, variant and motion persistence keys.
#define THEME_PERSIST_KEY 901
static inline bool theme_integer(Tuple *t, int32_t *v) {
  if (!t || (t->type != TUPLE_INT && t->type != TUPLE_UINT)) return false;
  if (t->length == 1) *v = t->type == TUPLE_INT ? t->value->int8 : t->value->uint8;
  else if (t->length == 2) *v = t->type == TUPLE_INT ? t->value->int16 : t->value->uint16;
  else if (t->length == 4) {
    if (t->type == TUPLE_UINT && t->value->uint32 > INT32_MAX) return false;
    *v = t->value->int32;
  } else return false;
  return true;
}
static inline void theme_restore(void) {
  int32_t value = persist_read_int(THEME_PERSIST_KEY);
  face_theme = persist_exists(THEME_PERSIST_KEY) && value >= 0 && value < THEME_COUNT ? value : 0;
  APP_LOG(APP_LOG_LEVEL_INFO, "Theme boot=%u", face_theme);
}
static inline bool theme_receive(DictionaryIterator *it) {
  int32_t value;
  if (!theme_integer(dict_find(it, MESSAGE_KEY_THEME), &value) || value < 0 || value >= THEME_COUNT) return false;
  if (value != face_theme && persist_write_int(THEME_PERSIST_KEY, value) != (int)sizeof(int32_t)) return false;
  face_theme = value;
  APP_LOG(APP_LOG_LEVEL_INFO, "Theme saved=%u", face_theme);
  return true;
}
static inline GColor theme_color(unsigned role) {
#ifdef PBL_COLOR
  return GColorFromHEX(theme_colors[face_theme][role]);
#else
  bool light = theme_light[face_theme];
  // Surface treatments: light tile/paper, dark ink; other themes reverse it.
  if (role == THEME_BG || role == THEME_SURFACE) return light ? GColorWhite : GColorBlack;
  return light ? GColorBlack : GColorWhite;
#endif
}
